version: "3.8"

services:
  mongodb:
    container_name: lushaDB
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    command: mongod --port $MONGODB_DOCKER_PORT
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_DOCKER_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db

volumes:
  db:
